Trying to fix echo cancellation issues
ubports/android_device_oneplus_bacon-1 pull request #11
Opened 2018-10-04 17:03 UTC by Flohack74

As per https://github.com/ubports/ubuntu-touch/issues/861

2018-10-07 07:59 UTC, APokorny commented
I think you have to set "persist.audio.dualmic.config=endfire" otherwise the hal library will not enable fluence for voicecal speaker voicerec voicecomm

2018-10-07 14:33 UTC, APokorny requested changes
I think you have to set "persist.audio.dualmic.config=endfire" otherwise the hal library will not enable fluence for voicecal speaker voicerec voicecomm.

2018-10-07 17:51 UTC, APokorny approved these changes

2018-10-07 17:51 UTC, merged

2020-03-13 04:47 UTC, ernesst commented
Was this commit successful to remove the echo ?  Why half of the modification were removed after ?